### ISSUE TITLE
do more efficient the pos binding in backend_kivyagg

### ISSUE THREAD

**Issue by andnovar** [kivy-garden/garden.matplotlib#12]
I tried to translate all the instructions to self.x and self.y but it did not work. For now the only way is to call draw() on_pos.

**Comment by dessant** [comment]
@andnovar, that is ok for the kivy backend.

For the agg backend we should not call draw() on pos change, but bind the texture and widget pos. Redrawing should only be needed on size change.

**Comment by andnovar** [comment]
https://github.com/kivy-garden/garden.matplotlib/pull/14
