### ISSUE TITLE
Unable to find backend_kivy when using local copy of matplotlib/numpy

### ISSUE THREAD

**Issue by 2Cubed** [kivy-garden/garden.matplotlib#13]
When running [test_backend.py](https://github.com/kivy-garden/garden.matplotlib/blob/master/examples/test_backend.py), everything goes normal when matplotlib and numpy are fully installed.
When trying to run with a local copy of matplotlib and numpy in the project directory, it crashes with the error:

``` python
ImportError: No module named 'kivy.garden.matplotlib.backend_kivy'
```

As there seems to be no way to install numpy successfully with pip, it would be impossible to compile this code for Android using buildozer. It seems to be a problem with the garden installation.

**Comment by matham** [comment]
I think this has been resolved already on IRC. In any case this doesn't seem like a bug and support issues like these are probably better better handled on the mailing lists.
