### ISSUE TITLE
Segmentation fault when used with kivy InteractiveLauncher

### ISSUE THREAD

**Issue by daldr-ntml** [kivy-garden/garden.matplotlib#24]
# Explanation

The script below plots a simple x,y graph in a tabbed panel using garden.matplotlib.

If the line 'INTERACTIVE_MODE = True' (in the entry point below) is as is, the kivy app is launched using the kivy InteractiveLauncher and a segmentation fault occurs (see test output below).

If INTERACTIVE_MODE is set to False, the kivy InteractiveLauncher is not used and the app launches without error.

(I want to use the InteractiveLauncher so that I can run other scripts from the REPL while the kivy app is running.  They need to run from the same REPL so that they can share objects.)
# Test environment

Fedora 22 on VirtualBox 4.3 (Windows host), kivy 1.9.1-dev  Python 3.4.2
# Test output

$ python3 main.py 
[INFO   ] [Logger      ] Record log in /home/osboxes/.kivy/logs/kivy_15-09-18_19.txt
[INFO   ] [Kivy        ] v1.9.1-dev
[INFO   ] [Python      ] v3.4.2 (default, Jul  9 2015, 17:24:30) 
[GCC 5.1.1 20150618 (Red Hat 5.1.1-4)]
[INFO   ] [Factory     ] 177 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] OpenGL version <b'2.1 Mesa 10.6.3 (git-ccef890)'>
[INFO   ] [GL          ] OpenGL vendor <b'VMware, Inc.'>
[INFO   ] [GL          ] OpenGL renderer <b'Gallium 0.4 on llvmpipe (LLVM 3.5, 128 bits)'>
[INFO   ] [GL          ] OpenGL parsed version: 2, 1
[INFO   ] [GL          ] Shading version <b'1.30'>
[INFO   ] [GL          ] Texture max size <8192>
[INFO   ] [GL          ] Texture max units <18>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
Segmentation fault (core dumped)
# main.py

```
#!/usr/bin/python3

from kivy.interactive import InteractiveLauncher
from kivy.app import App

import matplotlib
matplotlib.use('module://kivy.garden.matplotlib.backend_kivy')
from matplotlib.figure import Figure
from kivy.garden.matplotlib.backend_kivyagg import FigureCanvas,\
    NavigationToolbar2Kivy
from matplotlib.transforms import Bbox
import matplotlib.pyplot as plt

from kivy.uix.boxlayout import BoxLayout

def press(event):
    print('press released from test', event.x, event.y, event.button)

def release(event):
    print('release released from test', event.x, event.y, event.button)

def keypress(event):
    print('key down', event.key)

def keyup(event):
    print('key up', event.key)

def motionnotify(event):
    print('mouse move to ', event.x, event.y)

def resize(event):
    print('resize from mpl ', event)

def scroll(event):
    print('scroll event from mpl ', event.x, event.y, event.step)

def figure_enter(event):
    print('figure enter mpl')

def figure_leave(event):
    print('figure leaving mpl')

def close(event):
    print('closing figure')

def autolabel(rects):
    # attach some text labels
    for rect in rects:
        height = rect.get_height()
        ax.text(rect.get_x() + rect.get_width() / 2., 1.05 * height,
                '%d' % int(height), ha='center', va='bottom')

def callback(instance):
    autolabel(rects1)
    autolabel(rects2)
    canvas.draw()

class CMplGraph(BoxLayout):

    def __init__(self, **kwargs):
        super(CMplGraph, self).__init__(**kwargs)
        self.create_plot()

    def create_plot(self):

        fig, ax = plt.subplots()

        xCoords = [1,2,3]
        yCoords = [1,4,9]

        # Plot the data
        lineA = ax.plot(xCoords, yCoords, color='blue', marker='o', markerfacecolor='blue', markersize=6)
        ax.set_ylim([0, 10])

        # Connect Matplotlib events to our own callbacks using Matplotlib's mpl_connect method
        fig.canvas.mpl_connect('button_press_event', press)
        fig.canvas.mpl_connect('button_release_event', release)
        fig.canvas.mpl_connect('key_press_event', keypress)
        fig.canvas.mpl_connect('key_release_event', keyup)
        fig.canvas.mpl_connect('motion_notify_event', motionnotify)
        fig.canvas.mpl_connect('resize_event', resize)
        fig.canvas.mpl_connect('scroll_event', scroll)
        fig.canvas.mpl_connect('figure_enter_event', figure_enter)
        fig.canvas.mpl_connect('figure_leave_event', figure_leave)
        fig.canvas.mpl_connect('close_event', close)

        canvas = fig.canvas

        # Add each navigation toolbar and canvas to our BoxLayout
        nav1 = NavigationToolbar2Kivy(canvas)
        self.add_widget(nav1.actionbar)
        self.add_widget(canvas)

class GuiApp(App):
    pass

# Entry point

if __name__ == '__main__':
    INTERACTIVE_MODE = True
    if INTERACTIVE_MODE:
        launcher = InteractiveLauncher(GuiApp())
        launcher.run()
    else:
        GuiApp().run()
```
# gui.kv

```
<CMplGraph>:
    id: my_graph
    orientation: 'vertical'

TabbedPanel:
    id: tab_panel
    do_default_tab: False

    TabbedPanelItem:
        id: tab_graph
        text: 'Graph'
        CMplGraph:
```

**Comment by andnovar** [comment]
This is not a problem in this package: You get segmentation fault if you run this code as well with no matplotlib at all. It is related to these issues: https://github.com/kivy/kivy/issues/1862 , https://github.com/kivy/kivy/issues/3531 . backend_kivy uses Window for mouse events.

from kivy.interactive import InteractiveLauncher
from kivy.app import App
from kivy.uix.button import Button
from kivy.core.window import Window

class TestApp(App):
    def build(self):
        return Button(text='Hello World')

if **name** == '**main**':
    INTERACTIVE_MODE = False
    if INTERACTIVE_MODE:
        launcher = InteractiveLauncher(TestApp())
        launcher.run()
    else:
        TestApp().run()

This http://stackoverflow.com/questions/23573676/kivy-threads-queues-clocks-and-python-sockets might help if you want to share objects.
