### ISSUE TITLE
Strange behavior when combined with garden.graph

### ISSUE THREAD

**Issue by qherreros** [kivy-garden/garden.matplotlib#27]
When you use black_option to color all labels in black in a garden.graph widget (or red or any color), it does change the color of the matplotlib canvas accordingly (?!?) embedded into the App.
I can send you an example if needed.
![screenshot from 2015-10-09 12 01 39](https://cloud.githubusercontent.com/assets/7406885/10392297/b84d131e-6e7d-11e5-8a7a-88132a36ffe8.png)

**Comment by dessant** [comment]
Yes, please post a small, runnable example.

**Comment by qherreros** [comment]
Here is my code : https://trinket.io/python/225f3586f8

If you comment out label_option or if you change the color, you'll see the matplotlib widget change

**Comment by dessant** [comment]
Could you post it with indentation?

**Comment by qherreros** [comment]
I've updated my previous post : 
https://trinket.io/python/225f3586f8
