### ISSUE TITLE
matplotlib v3.8.0 and past not compatible

### ISSUE THREAD

**Issue by Fretless14** [kivy-garden/garden.matplotlib#84]
For the life of me I can't get plots to show up in my kivy application.

Is it compatible with Python 3.11.6 and matplotlib 3.8.1?

What are the version requirements?

**Comment by Fretless14** [comment]
Jk it was matplotlib, had to install a version prior to 3.8.0;

`pip install "matplotlib<3.8.0"`

**Comment by mp-007** [comment]
@Fretless14 my version is compatible with 3.8 (note: for android you need 3.5.2)
https://github.com/mp-007/kivy_matplotlib_widget
